# --- !Ups
CREATE TABLE ACCOUNT(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  IS_ADMIN BOOLEAN DEFAULT false,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT NULL,
  DELETED_AT DATETIME DEFAULT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;

INSERT INTO ACCOUNT (USER_NAME, PASSWORD, IS_ADMIN) VALUES ('admin', 'passwd', true);

# --- !Downs
DROP TABLE ACCOUNT;